import Head from "next/head";
const MetaData = () => {
  return (
    <Head>
      <title>LAD 13</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default MetaData;
